nohup: ignoring input
[2024-05-10 05:09:11,632] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/root/anaconda3/envs/deepseek/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
[93m [WARNING] [0m NVIDIA Inference is only supported on Ampere and newer architectures
[93m [WARNING] [0m sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
[93m [WARNING] [0m using untested triton version (2.3.0), only 1.0.0 is known to be compatible
Loading checkpoint shards:   0%|          | 0/7 [00:00<?, ?it/s]Loading checkpoint shards:  14%|█▍        | 1/7 [00:01<00:07,  1.31s/it]Loading checkpoint shards:  29%|██▊       | 2/7 [00:02<00:07,  1.49s/it]Loading checkpoint shards:  43%|████▎     | 3/7 [00:04<00:05,  1.44s/it]Loading checkpoint shards:  57%|█████▋    | 4/7 [00:06<00:04,  1.54s/it]Loading checkpoint shards:  71%|███████▏  | 5/7 [00:07<00:03,  1.61s/it]Loading checkpoint shards:  86%|████████▌ | 6/7 [00:09<00:01,  1.57s/it]Loading checkpoint shards: 100%|██████████| 7/7 [00:10<00:00,  1.45s/it]Loading checkpoint shards: 100%|██████████| 7/7 [00:10<00:00,  1.49s/it]
/root/anaconda3/envs/deepseek/lib/python3.10/site-packages/datasets/load.py:1486: FutureWarning: The repository for lukaemon/mmlu contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/lukaemon/mmlu
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(
